name: Bash workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install pyyaml
      - name: Make bash
        run: python workflow.py > workflow.bash
      - name: Artefact workflow
        uses: actions/upload-artifact@v2
        with:
          name: workflow
          path: workflow.bash
